<h1>Импорт библиотек

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [4]:
import numpy as np


def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''

    result = 0
    for i in range(len(X)):
        result += np.dot(X[i], V[i])
    return result


def test_1():
    X = np.array([
        np.array([
            [1, 2],
            [3, 4]
        ]),
        np.array([
            [5, 6],
            [7, 8]
        ])
    ])

    V = np.array([
        np.array([
            [5],
            [1]
        ]),
        np.array([
            [9],
            [1]
        ])
    ])
    return sum_prod(X, V)


def test_2():
    X = np.array([
        np.array([
            [4, 1],
            [8, 9]
        ]),
        np.array([
            [4, 2],
            [6, 1]
        ])
    ])

    V = np.array([
        np.array([
            [3],
            [1]
        ]),
        np.array([
            [2],
            [1]
        ])
    ])
    return sum_prod(X, V)


print(test_1())
print()
print(test_2())

[[58]
 [90]]

[[23]
 [46]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [5]:
import numpy as np


def binarize(M, threshold=0.5):
    if M.dtype != float and M.dtype != int:
        return "Неверные данные"
    return np.where(M > threshold, 1, 0)


def test_1():
    M = np.array([[0.1, 0.6],
                  [0.7, 0.2]])
    return binarize(M)


def test_2():
    M = np.array([[10, 20],
                  [30, 40]])
    return binarize(M)


def test_3():
    M = np.array([[0, 0],
                  [0, 0]])
    return binarize(M)


def test_4():
    M = np.array([[0.7, 0.55],
                  [0.61, 0.8]])
    return binarize(M)


def test_5():
    M = np.array([[1, 'a'],
                  [0.2, 0.8]])
    return binarize(M)


print(test_1())
print()
print(test_2())
print()
print(test_3())
print()
print(test_4())
print()
print(test_5())

[[0 1]
 [1 0]]

[[1 1]
 [1 1]]

[[0 0]
 [0 0]]

[[1 1]
 [1 1]]

Неверные данные


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [6]:
import numpy as np


def unique_rows(mat):
    arr = []
    for row in mat:
        arr.append(np.unique(row))
    return arr


def unique_columns(mat):
    arr = []
    for column in mat.T:
        arr.append(np.unique(column))
    return arr


def test_1():
    mat = np.array(
        [
            [1, 0, 4],
            [6, 10, 5],
            [2, 8, 7]
        ])

    print(f"Уникальные элементы в каждой строке: {unique_rows(mat)}")
    print(f"Уникальные элементы в каждом столбце: {unique_columns(mat)}")
    print()


def test_2():
    mat = np.array(
        [
            [1, 2, 1],
            [1, 1, 3],
            [5, 1, 1]
        ])

    print(f"Уникальные элементы в каждой строке: {unique_rows(mat)}")
    print(f"Уникальные элементы в каждом столбце: {unique_columns(mat)}")
    print()


def test_3():
    mat = np.array(
        [
            [1, 1, 1],
            [1, 1, 1],
            [1, 1, 1]
        ])

    print(f"Уникальные элементы в каждой строке: {unique_rows(mat)}")
    print(f"Уникальные элементы в каждом столбце: {unique_columns(mat)}")
    print()


def test_4():
    mat = np.array(
        [
            [0, 0],
            [0, 0],
        ])

    print(f"Уникальные элементы в каждой строке: {unique_rows(mat)}")
    print(f"Уникальные элементы в каждом столбце: {unique_columns(mat)}")
    print()


test_1()
test_2()
test_3()
test_4()

Уникальные элементы в каждой строке: [array([0, 1, 4]), array([ 5,  6, 10]), array([2, 7, 8])]
Уникальные элементы в каждом столбце: [array([1, 2, 6]), array([ 0,  8, 10]), array([4, 5, 7])]

Уникальные элементы в каждой строке: [array([1, 2]), array([1, 3]), array([1, 5])]
Уникальные элементы в каждом столбце: [array([1, 5]), array([1, 2]), array([1, 3])]

Уникальные элементы в каждой строке: [array([1]), array([1]), array([1])]
Уникальные элементы в каждом столбце: [array([1]), array([1]), array([1])]

Уникальные элементы в каждой строке: [array([0]), array([0])]
Уникальные элементы в каждом столбце: [array([0]), array([0])]



<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [1]:
import numpy as np


def chess(m, n, a, b):
    if type(m) != int or type(n) != int or type(a) != int or type(b) != int or m < 0 or n < 0:
        return "Неверные данные"
    chessboard = np.ones((m, n))
    for i in range(m):
        for j in range(n):
            if (i + j) % 2 == 0:
                chessboard[i, j] = a
            else:
                chessboard[i, j] = b
    return chessboard


def test_1():
    return chess(5, 5, 1, 2)


def test_2():
    return chess(4, 2, 0, 1)


def test_3():
    return chess(2, 6, 3, -4)


def test_4():
    return chess(-1, 6, 3, 4)


def test_5():
    return chess(1, 'abc', 3, 4)


def test_6():
    return chess(1, 8, 'a', 4)


print(test_1())
print()
print(test_2())
print()
print(test_3())
print()
print(test_4())
print()
print(test_5())
print()
print(test_6())

[[1. 2. 1. 2. 1.]
 [2. 1. 2. 1. 2.]
 [1. 2. 1. 2. 1.]
 [2. 1. 2. 1. 2.]
 [1. 2. 1. 2. 1.]]

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]

[[ 3. -4.  3. -4.  3. -4.]
 [-4.  3. -4.  3. -4.  3.]]

Неверные данные

Неверные данные

Неверные данные


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [8]:
import numpy as np


def one_hot_encoding(vector):
    num_classes = np.max(vector) + 1
    num_samples = len(vector)
    encoded_vector = np.zeros((num_samples, num_classes))
    encoded_vector[np.arange(num_samples), vector] = 1
    return encoded_vector


def test_1():
    return one_hot_encoding([0, 2, 3, 0])


def test_2():
    return one_hot_encoding([2, 3, 4, 0])


def test_3():
    return one_hot_encoding([3, 4, 2, 1])


def test_4():
    return one_hot_encoding([5, 0, 4])


def test_5():
    return one_hot_encoding([0, 0, 0])


def test_6():
    return one_hot_encoding([2, 2, 2])


print(test_1())
print()
print(test_2())
print()
print(test_3())
print()
print(test_4())
print()
print(test_5())
print()
print(test_6())

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

[[1.]
 [1.]
 [1.]]

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
